In [2]:
import numpy as np

In [4]:


point1 = np.array([0.1186, 1.6733, 0.9878])
point2 = np.array([-0.1189, 1.6661, 0.9894])
point3 = np.array([-0.1269, 1.2560, 0.9859])

'''
point1 = np.array([0.1267, 1.2877,0.9845])
point2 = np.array([0.1186, 1.6733, 0.9878])
point3 = np.array([-0.1269, 1.2560, 0.9859])
 
point1 = np.array([0.1186, 1.6733, 0.9878])
point2 = np.array([0.1267, 1.2877,0.9845])
point3 = np.array([-0.1269, 1.2560, 0.9859])

point1 = np.array([2.4779, 0.2682, 0.0630])
point2 = np.array([2.7506, 0.0014, 0.0636])
point3 = np.array([2.4835, -0.2715, 0.062])
'''

'\npoint1 = np.array([0.1267, 1.2877,0.9845])\npoint2 = np.array([0.1186, 1.6733, 0.9878])\npoint3 = np.array([-0.1269, 1.2560, 0.9859])\n \npoint1 = np.array([0.1186, 1.6733, 0.9878])\npoint2 = np.array([0.1267, 1.2877,0.9845])\npoint3 = np.array([-0.1269, 1.2560, 0.9859])\n\npoint1 = np.array([2.4779, 0.2682, 0.0630])\npoint2 = np.array([2.7506, 0.0014, 0.0636])\npoint3 = np.array([2.4835, -0.2715, 0.062])\n'

In [6]:
# Compute vectors from point1 to point2 and point1 to point3
v1 = point2 - point1
v2 = point3 - point1
print(v1, v2)

[-0.2375 -0.0072  0.0016] [-0.2455 -0.4173 -0.0019]


In [8]:
# Calculate the normal vector (cross product of v1 and v2)
normal_vector = np.cross(v1, v2)
normal_vector

array([ 0.00068136, -0.00084405,  0.09734115])

In [10]:
# Normalize the normal vector
normal_vectorN = normal_vector / np.linalg.norm(normal_vector)

In [12]:
normal_vectorN

array([ 0.00699928, -0.00867051,  0.99993791])

In [14]:
# Calculate pitch, roll, and yaw (assuming normal vector is [a, b, c])
a, b, c = normal_vectorN

In [16]:
# Pitch: angle with the xy-plane
pitch = np.arctan2(b, np.sqrt(a**2 + c**2))

# Roll: angle with the xz-plane
roll = np.arctan2(a, np.sqrt(b**2 + c**2))

# Yaw: angle with the yz-plane
yaw = np.arctan2(c, np.sqrt(a**2 + b**2))

# Convert angles from radians to degrees
pitch_deg = np.degrees(pitch)
roll_deg = np.degrees(roll)
yaw_deg = np.degrees(yaw)

# Output the results
print(f"Normal Vector: {normal_vectorN}")
print(f"Pitch (degrees): {pitch_deg}")
print(f"Roll (degrees): {roll_deg}")
print(f"Yaw (degrees): {yaw_deg}")

Normal Vector: [ 0.00699928 -0.00867051  0.99993791]
Pitch (degrees): -0.4967899610974185
Roll (degrees): 0.4010323208660527
Yaw (degrees): 89.36153680693215
